import time

print("\nHELP PAGE\n---------------")
time.sleep(0.4)
print("ddos:\nThis command opens a ddos spam attack on any ip\n-----")
time.sleep(0.4)
print("ip a:\nThis command gets your public ip address\n-----")
print("help:\nThis command displays the help page\n-----")
time.sleep(0.4)
print("play-sw:\nThis command starts StarWars\n-----")
time.sleep(0.4)
print("ping:\nthis command opens an ip pinger\n-----")
print("discord-gift:\nGenerates and checks for valid discord nitro codes\n-----")
time.sleep(0.4)
print("accgen:\nthis command opens an multi account user checker\n-----")
print("cpu:\nChecks your cpu usage\n-----")
print("ram:\nChecks your ram usage\n-----")
time.sleep(0.2)
print("disk:\nChecks your disk usage\n-----")
time.sleep(0.2)
print("about:\nAbout Replux\n-----")
